# Generated by Django 4.2.6 on 2023-11-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('title', models.CharField(max_length=100, verbose_name='название образовательного модуля')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'образовательный модуль',
                'verbose_name_plural': 'образовательные модули',
            },
        ),
    ]
