version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=diplom
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5434:5433'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    volumes:
      - .:/code
    command: bash -c 'python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000'
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data:
